language: java

script:
  - cd aula-01/java && mvn clean checkstyle:check verify -P cobertura spotbugs:spotbugs
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
jdk:
  - oraclejdk8
